version: '3.3'

services:
  # Postgres
  db:
    image: postgres
    environment:
      - POSTGRES_USER=ci
      - POSTGRES_PASSWORD=ci
      - POSTGRES_DB=vims

  web:
    build: .
    volumes:
      - .:/docker_django
    ports:
      - "8000:8000"
    links:
      - db
    depends_on:
      - db
