# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 17:59
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('phone', models.CharField(max_length=25, validators=[django.core.validators.RegexValidator('^[0-9() -]{6,25}$')], verbose_name='Phone')),
                ('street_number', models.IntegerField(blank=True, null=True, verbose_name='Street number')),
                ('floor', models.SmallIntegerField(blank=True, null=True, verbose_name='Floor')),
                ('apartment', models.IntegerField(blank=True, null=True, verbose_name='Apartment')),
                ('zipcode', models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator('^\\d{5}$|^\\d{7}$')], verbose_name='Zipcode')),
                ('street', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_profiles', to='geography.Street', verbose_name='Street')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
