# Generated by Django 2.0 on 2017-12-24 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0004_recipient_uid'),
        ('users', '0003_auto_20171120_1005'),
        ('adoptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='adoption',
            unique_together={('adopter', 'recipient')},
        ),
    ]
