# Generated by Django 2.0.2 on 2018-02-26 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0003_status_set_at_triggers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='modified_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Modified at'),
        ),
        migrations.RunSQL('''
            UPDATE
                adoptions_delivery
            SET
                planned_delivery_date = created_at::date
            WHERE
                planned_delivery_date IS NULL;
        '''),
        migrations.AlterField(
            model_name='delivery',
            name='planned_delivery_date',
            field=models.DateField(blank=True, verbose_name='Planned delivery date'),
        ),
    ]
