# Generated by Django 2.0 on 2017-12-29 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20171120_1005'),
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityDayVolunteer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('activity_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='activities.ActivityDay', verbose_name='Activity day')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='users.UserProfile', verbose_name='Volunteer')),
            ],
            options={
                'verbose_name_plural': 'Activity days volunteers',
                'verbose_name': 'Activity day volunteer',
            },
        ),
        migrations.AlterUniqueTogether(
            name='activitydayvolunteer',
            unique_together={('volunteer', 'activity_day')},
        ),
    ]
