# Generated by Django 2.0 on 2017-12-29 14:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogisticsCenter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('description', models.TextField(unique=True, verbose_name='Description')),
                ('street_number', models.IntegerField(verbose_name='Street number')),
                ('contact_person', models.CharField(blank=True, max_length=150, null=True, verbose_name='Contact person')),
                ('phone', models.CharField(blank=True, max_length=25, null=True, validators=[django.core.validators.RegexValidator('^[0-9() -]{6,25}$')], verbose_name='Phone')),
                ('street', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logistics_centers', to='geography.Street', verbose_name='Street')),
            ],
            options={
                'verbose_name': 'Logistics center',
                'verbose_name_plural': 'Logistics centers',
            },
        ),
    ]
