# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 09:22
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='recipient_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('holocaust-survivor', 'Holocaust survivor'), ('handicapped', 'Handicapped'), ('avrech', 'Avrech'), ('domestic-violence', 'Domestic violence'), ('new-immigrant', 'New immigrant'), ('unhealthy', 'Unhealthy'), ('senior-citizen', 'Senior citizen')], max_length=30, verbose_name='Recipient tag'), size=None, verbose_name='Recipient tags'),
        ),
    ]
