# Generated by Django 2.0 on 2017-12-05 22:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0002_auto_20171127_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='recipient_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('holocaust-survivor', 'Holocaust survivor'), ('handicapped', 'Handicapped'), ('avrech', 'Avrech'), ('domestic-violence', 'Domestic violence'), ('general', 'General'), ('unhealthy', 'Unhealthy'), ('single-parent', 'Single parent')], max_length=30, verbose_name='Recipient tag'), size=None, verbose_name='Recipient tags'),
        ),
        migrations.RunSQL("""
            UPDATE
                recipients_recipient
            SET
                recipient_tags = ARRAY_REPLACE(ARRAY_REPLACE(recipient_tags, 'new-immigrant', 'general'), 'senior-citizen', 'single-parent');
        """),
    ]
