# Generated by Django 2.0 on 2017-12-12 11:46

from django.db import migrations, models
import uuid


def populate_uid_forwards(apps, schema_editor):
    Recipient = apps.get_model('recipients', 'Recipient')
    for r in Recipient.objects.all():
        r.uid = uuid.uuid4()
        r.save(update_fields=('uid',))


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('recipients', '0003_auto_20171206_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='ID'),
        ),
        migrations.RunPython(
            populate_uid_forwards,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='recipient',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='ID'),
        ),
    ]
