# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 18:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('gov_id', models.IntegerField(unique=True, verbose_name='Government ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('county_gov_id', models.IntegerField(verbose_name='County government ID')),
                ('county_name', models.CharField(max_length=100, verbose_name='County name')),
                ('municipality_gov_id', models.IntegerField(verbose_name='Municipality government ID')),
                ('municipality_name', models.CharField(max_length=100, verbose_name='Municipality name')),
            ],
            options={
                'verbose_name_plural': 'Settlements',
                'verbose_name': 'Settlement',
            },
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('gov_id', models.IntegerField(verbose_name='Government ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geography.Settlement', verbose_name='Settlement')),
            ],
            options={
                'verbose_name_plural': 'Streets',
                'verbose_name': 'Street',
            },
        ),
        migrations.AlterUniqueTogether(
            name='street',
            unique_together=set([('settlement', 'gov_id')]),
        ),
    ]
